In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
salaries = pd.read_csv('salaries_data.csv')

salaries_test = pd.read_csv('testeo.csv')

In [3]:
salaries.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           500 non-null    int64
 1   experience_level    500 non-null    object
 2   employment_type     500 non-null    object
 3   job_title           500 non-null    object
 4   salary              500 non-null    int64
 5   salary_currency     500 non-null    object
 6   salary_in_usd       500 non-null    int64
 7   employee_residence  500 non-null    object
 8   remote_ratio        500 non-null    int64
 9   company_location    500 non-null    object
 10  company_size        500 non-null    object
dtypes: int64(4), object(7)
memory usage: 224.3 KB

In [4]:
salaries_test.head()

,work_year,experience_level,employment_type,job_title,employee_residence,remote_ratio,company_location,company_size
0,2020,SE,FT,Machine Learning Scientist,JP,0,JP,S
1,2020,MI,FT,Lead Data Analyst,US,100,US,L
2,2020,MI,FT,Data Analyst,US,100,US,L
3,2020,MI,FT,Machine Learning Engineer,CN,0,CN,M
4,2020,MI,FT,Product Data Analyst,IN,100,IN,L

In [5]:
salaries.drop(columns=['salary', 'salary_currency'], inplace=True)

salaries.head()

,work_year,experience_level,employment_type,job_title,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2022,SE,FT,Data Engineer,140250,US,100,US,M
1,2022,SE,FT,Data Engineer,135000,US,100,US,M
2,2021,MI,FT,BI Data Analyst,100000,US,100,US,M
3,2021,MI,CT,ML Engineer,270000,US,100,US,L
4,2021,MI,FT,Data Engineer,26005,RO,0,US,L

In [6]:
from sklearn.preprocessing import LabelEncoder               


le=LabelEncoder()

for c in salaries.columns:
    
    if salaries.dtypes[c]==object:
        
        le.fit(salaries[c].astype(str))
        
        salaries[c]=le.transform(salaries[c].astype(str))

In [7]:
salaries.head()

,work_year,experience_level,employment_type,job_title,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2022,3,2,17,140250,47,100,41,1
1,2022,3,2,17,135000,47,100,41,1
2,2021,2,2,5,100000,47,100,41,1
3,2021,2,0,36,270000,47,100,41,0
4,2021,2,2,17,26005,40,0,41,0

In [8]:
from sklearn.preprocessing import LabelEncoder               


le=LabelEncoder()

for c in salaries_test.columns:
    
    if salaries_test.dtypes[c]==object:
        
        le.fit(salaries_test[c].astype(str))
        
        salaries_test[c]=le.transform(salaries_test[c].astype(str))

In [9]:
salaries_test.head()

,work_year,experience_level,employment_type,job_title,employee_residence,remote_ratio,company_location,company_size
0,2020,3,1,22,17,0,18,2
1,2020,2,1,18,25,100,23,0
2,2020,2,1,8,25,100,23,0
3,2020,2,1,20,4,0,4,1
4,2020,2,1,27,14,100,15,0

In [10]:
X = salaries.drop(columns=['salary_in_usd'])

y = salaries['salary_in_usd']

In [11]:
from sklearn.model_selection import train_test_split as tts

X_train, X_test, y_train, y_test  = tts(X, y, train_size=0.8, test_size=0.2, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((400, 8), (100, 8), (400,), (100,))

In [12]:
from sklearn.linear_model import LinearRegression as LinReg   # alias es mio

from sklearn.linear_model import Lasso        # regularizacion L1
from sklearn.linear_model import Ridge        # regularizacion L2
from sklearn.linear_model import ElasticNet   # regularizacion L1+L2


# se inician los modelos

linreg=LinReg()
lasso=Lasso()
ridge=Ridge()
elastic=ElasticNet()

In [13]:
from sklearn.svm import SVR  # support vector regressor

svr=SVR()

In [14]:
from sklearn.ensemble import RandomForestRegressor as RFR  

from sklearn.tree import ExtraTreeRegressor as ETR

rfr=RFR()

etr=ETR()

In [19]:
%pip install xgboost
#%pip install catboost

%conda install lightgbm

Requirement already satisfied: xgboost in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (1.7.4)
Requirement already satisfied: numpy in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from xgboost) (1.21.5)
Requirement already satisfied: scipy in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from xgboost) (1.9.1)
Note: you may need to restart the kernel to use updated packages.
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: \
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/osx-64::holoviews==1.15.0=py39hecd8cb5_0
  - defaults/noarch::nbclassic==0.3.5=pyhd3eb1b0_0
  - defaults/osx-64::jupyterlab==3.4.4=py39hecd8cb5_0
  - defaults/osx-64::anaconda==2022.10=py39_0
  - defaults/osx-64::hvplot==0.8.0=py39hecd8cb5_0
  - defaults/osx-64::qtconsole==5.3.2=py39hecd8cb5_0
  - defaults/osx-64::ipython==7.31.1=py39hecd8cb5_1
  - defaults/osx-64::sphinx==5.0.2=py39hecd8cb5_0
  - defaults/osx-64::_ipyw_jlab_nb_ext_conf==0.1.0=py39hecd8cb5_1
  - defaults/noarch::jupyterlab_pygments==0.1.2=py_0
  - defaults/osx-64::jupyter_server==1.18.1=py39hecd8cb5_0
  - defaults/osx-64::spyder-kernels==2.3.3=py39hecd8cb5_0
  - defaults/noarch::jupyterlab_server==2.10.3=pyhd3eb1b0_1
  - defaults/osx-64::nbconvert==6.4.4=py39hecd8cb5_0
  - defaults/osx-64::numpydoc==1.4.0=py39hecd8cb5_0
  - defaults/osx-64::jupyter==1.0.0=py39hecd8cb5_8
  - defaults/noarch::ipywidgets==7.6.5=pyhd3eb1b0_1
  - defaults/noarch::jupyter_console==6.4.3=pyhd3eb1b0_0
  - defaults/osx-64::ipykernel==6.15.2=py39hecd8cb5_0
  - defaults/osx-64::spyder==5.3.3=py39hecd8cb5_0
  - defaults/osx-64::notebook==6.4.12=py39hecd8cb5_0
  - defaults/osx-64::widgetsnbextension==3.5.2=py39hecd8cb5_0
done

## Package Plan ##

  environment location: /Users/fernando/opt/anaconda3

  added / updated specs:
    - lightgbm


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-23.1.0               |   py39hecd8cb5_0         938 KB
    lightgbm-3.3.5             |   py39hcec6c5f_0         1.1 MB
    ------------------------------------------------------------
                                           Total:         2.1 MB

The following NEW packages will be INSTALLED:

  lightgbm           pkgs/main/osx-64::lightgbm-3.3.5-py39hcec6c5f_0
  pygments           pkgs/main/noarch::pygments-2.11.2-pyhd3eb1b0_0

The following packages will be UPDATED:

  conda              conda-forge::conda-22.11.1-py39h6e949~ --> pkgs/main::conda-23.1.0-py39hecd8cb5_0



Downloading and Extracting Packages
conda-23.1.0         | 938 KB    |                                       |   0%
conda-23.1.0         | 938 KB    | 6                                     |   2%
conda-23.1.0         | 938 KB    | #####                                 |  14%
conda-23.1.0         | 938 KB    | ###########3                          |  31%
lightgbm-3.3.5       | 1.1 MB    | #########5                            |  26%
conda-23.1.0         | 938 KB    | #############################         |  79%
conda-23.1.0         | 938 KB    | ##################################### | 100%
lightgbm-3.3.5       | 1.1 MB    | #########################7            |  70%
lightgbm-3.3.5       | 1.1 MB    | ###############################2      |  85%
lightgbm-3.3.5       | 1.1 MB    | ##################################### | 100%


Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [20]:

from sklearn.ensemble import GradientBoostingRegressor as GBR

from xgboost import XGBRegressor as XGBR

from catboost import CatBoostRegressor as CTR

from lightgbm import LGBMRegressor as LGBMR


gbr=GBR()
xgbr=XGBR()
ctr=CTR()
lgbmr=LGBMR()

In [21]:
%pip install lazypredict

Collecting lazypredict
  Downloading lazypredict-0.2.12-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: scikit-learn in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from lazypredict) (1.0.2)
Requirement already satisfied: tqdm in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from lazypredict) (4.64.1)
Requirement already satisfied: pandas in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from lazypredict) (1.4.4)
Requirement already satisfied: joblib in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from lazypredict) (1.1.0)
Requirement already satisfied: xgboost in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from lazypredict) (1.7.4)
Requirement already satisfied: click in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from lazypredict) (8.0.4)
Requirement already satisfied: lightgbm in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from lazypredict) (3.3.5)
Requirement already satisfied: numpy in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from lightgbm->lazypredict) (1.21.5)
Requirement already satisfied: wheel in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from lightgbm->lazypredict) (0.37.1)
Requirement already satisfied: scipy in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from lightgbm->lazypredict) (1.9.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn->lazypredict) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from pandas->lazypredict) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from pandas->lazypredict) (2022.1)
Requirement already satisfied: six>=1.5 in /Users/fernando/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas->lazypredict) (1.16.0)
Installing collected packages: lazypredict
Successfully installed lazypredict-0.2.12
Note: you may need to restart the kernel to use updated packages.

In [22]:
from lazypredict.Supervised import LazyRegressor 

lazy=LazyRegressor()

lazy

In [24]:
linreg.fit(X_train, y_train)
lasso.fit(X_train, y_train)
ridge.fit(X_train, y_train)
elastic.fit(X_train, y_train)
svr.fit(X_train, y_train)
rfr.fit(X_train, y_train)
etr.fit(X_train, y_train)
gbr.fit(X_train, y_train)
xgbr.fit(X_train, y_train)
ctr.fit(X_train, y_train, verbose=0)
lgbmr.fit(X_train, y_train)
lazy.fit(X_train, X_test, y_train, y_test)

100%|██████████| 42/42 [00:02<00:00, 16.71it/s]

(                               Adjusted R-Squared  R-Squared       RMSE  \
 Model
 HistGradientBoostingRegressor                0.34       0.40   48641.98
 LGBMRegressor                                0.33       0.39   48945.21
 PassiveAggressiveRegressor                   0.26       0.32   51474.88
 HuberRegressor                               0.25       0.31   51816.56
 KNeighborsRegressor                          0.22       0.29   52865.45
 ElasticNet                                   0.22       0.28   53011.51
 OrthogonalMatchingPursuitCV                  0.22       0.28   53081.86
 BayesianRidge                                0.22       0.28   53126.04
 RidgeCV                                      0.21       0.28   53195.37
 LassoCV                                      0.21       0.28   53222.17
 LassoLars                                    0.21       0.28   53225.86
 Ridge                                        0.21       0.28   53228.10
 Lasso                                        0.21       0.28   53231.09
 LarsCV                                       0.21       0.28   53231.47
 LinearRegression                             0.21       0.28   53231.47
 LassoLarsIC                                  0.21       0.28   53231.47
 TransformedTargetRegressor                   0.21       0.28   53231.47
 LassoLarsCV                                  0.21       0.28   53231.47
 Lars                                         0.21       0.28   53231.47
 SGDRegressor                                 0.21       0.27   53326.58
 TweedieRegressor                             0.20       0.27   53540.37
 GammaRegressor                               0.19       0.26   53880.80
 OrthogonalMatchingPursuit                    0.18       0.25   54164.02
 PoissonRegressor                             0.13       0.20   56033.34
 RANSACRegressor                              0.10       0.17   56881.06
 RandomForestRegressor                        0.09       0.17   57131.19
 AdaBoostRegressor                            0.08       0.15   57664.75
 BaggingRegressor                             0.07       0.15   57778.98
 ExtraTreesRegressor                          0.06       0.14   58120.24
 ElasticNetCV                                -0.05       0.03   61499.86
 NuSVR                                       -0.09      -0.00   62588.24
 DummyRegressor                              -0.09      -0.00   62674.87
 QuantileRegressor                           -0.10      -0.02   63041.06
 SVR                                         -0.11      -0.02   63053.39
 ExtraTreeRegressor                          -0.15      -0.06   64341.41
 GradientBoostingRegressor                   -0.20      -0.10   65576.87
 XGBRegressor                                -0.25      -0.14   66932.57
 DecisionTreeRegressor                       -0.37      -0.26   70289.36
 KernelRidge                                 -3.18      -2.84  122626.58
 LinearSVR                                   -3.42      -3.06  126076.52
 MLPRegressor                                -3.44      -3.08  126374.88
 GaussianProcessRegressor                 -4702.81   -4322.71 4113133.19

                                Time Taken
 Model
 HistGradientBoostingRegressor        0.23
 LGBMRegressor                        0.16
 PassiveAggressiveRegressor           0.03
 HuberRegressor                       0.01
 KNeighborsRegressor                  0.01
 ElasticNet                           0.00
 OrthogonalMatchingPursuitCV          0.01
 BayesianRidge                        0.01
 RidgeCV                              0.00
 LassoCV                              0.03
 LassoLars                            0.00
 Ridge                                0.00
 Lasso                                0.00
 LarsCV                               0.01
 LinearRegression                     0.00
 LassoLarsIC                          0.01
 TransformedTargetRegressor           0.00
 LassoLarsCV                          0.01
 Lars                                 0.01
 SGDRegressor                         0.00
 TweedieRegressor                     0.01
 GammaRegressor                       0.01
 OrthogonalMatchingPursuit            0.00
 PoissonRegressor                     0.01
 RANSACRegressor                      0.03
 RandomForestRegressor                0.11
 AdaBoostRegressor                    0.03
 BaggingRegressor                     0.02
 ExtraTreesRegressor                  0.08
 ElasticNetCV                         0.03
 NuSVR                                0.02
 DummyRegressor                       0.00
 QuantileRegressor                    1.08
 SVR                                  0.02
 ExtraTreeRegressor                   0.01
 GradientBoostingRegressor            0.03
 XGBRegressor                         0.21
 DecisionTreeRegressor                0.01
 KernelRidge                          0.01
 LinearSVR                            0.01
 MLPRegressor                         0.21
 GaussianProcessRegressor             0.03  ,
                                Adjusted R-Squared  R-Squared       RMSE  \
 Model
 HistGradientBoostingRegressor                0.34       0.40   48641.98
 LGBMRegressor                                0.33       0.39   48945.21
 PassiveAggressiveRegressor                   0.26       0.32   51474.88
 HuberRegressor                               0.25       0.31   51816.56
 KNeighborsRegressor                          0.22       0.29   52865.45
 ElasticNet                                   0.22       0.28   53011.51
 OrthogonalMatchingPursuitCV                  0.22       0.28   53081.86
 BayesianRidge                                0.22       0.28   53126.04
 RidgeCV                                      0.21       0.28   53195.37
 LassoCV                                      0.21       0.28   53222.17
 LassoLars                                    0.21       0.28   53225.86
 Ridge                                        0.21       0.28   53228.10
 Lasso                                        0.21       0.28   53231.09
 LarsCV                                       0.21       0.28   53231.47
 LinearRegression                             0.21       0.28   53231.47
 LassoLarsIC                                  0.21       0.28   53231.47
 TransformedTargetRegressor                   0.21       0.28   53231.47
 LassoLarsCV                                  0.21       0.28   53231.47
 Lars                                         0.21       0.28   53231.47
 SGDRegressor                                 0.21       0.27   53326.58
 TweedieRegressor                             0.20       0.27   53540.37
 GammaRegressor                               0.19       0.26   53880.80
 OrthogonalMatchingPursuit                    0.18       0.25   54164.02
 PoissonRegressor                             0.13       0.20   56033.34
 RANSACRegressor                              0.10       0.17   56881.06
 RandomForestRegressor                        0.09       0.17   57131.19
 AdaBoostRegressor                            0.08       0.15   57664.75
 BaggingRegressor                             0.07       0.15   57778.98
 ExtraTreesRegressor                          0.06       0.14   58120.24
 ElasticNetCV                                -0.05       0.03   61499.86
 NuSVR                                       -0.09      -0.00   62588.24
 DummyRegressor                              -0.09      -0.00   62674.87
 QuantileRegressor                           -0.10      -0.02   63041.06
 SVR                                         -0.11      -0.02   63053.39
 ExtraTreeRegressor                          -0.15      -0.06   64341.41
 GradientBoostingRegressor                   -0.20      -0.10   65576.87
 XGBRegressor                                -0.25      -0.14   66932.57
 DecisionTreeRegressor                       -0.37      -0.26   70289.36
 KernelRidge                                 -3.18      -2.84  122626.58
 LinearSVR                                   -3.42      -3.06  126076.52
 MLPRegressor                                -3.44      -3.08  126374.88
 GaussianProcessRegressor                 -4702.81   -4322.71 4113133.19

                                Time Taken
 Model
 HistGradientBoostingRegressor        0.23
 LGBMRegressor                        0.16
 PassiveAggressiveRegressor           0.03
 HuberRegressor                       0.01
 KNeighborsRegressor                  0.01
 ElasticNet                           0.00
 OrthogonalMatchingPursuitCV          0.01
 BayesianRidge                        0.01
 RidgeCV                              0.00
 LassoCV                              0.03
 LassoLars                            0.00
 Ridge                                0.00
 Lasso                                0.00
 LarsCV                               0.01
 LinearRegression                     0.00
 LassoLarsIC                          0.01
 TransformedTargetRegressor           0.00
 LassoLarsCV                          0.01
 Lars                                 0.01
 SGDRegressor                         0.00
 TweedieRegressor                     0.01
 GammaRegressor                       0.01
 OrthogonalMatchingPursuit            0.00
 PoissonRegressor                     0.01
 RANSACRegressor                      0.03
 RandomForestRegressor                0.11
 AdaBoostRegressor                    0.03
 BaggingRegressor                     0.02
 ExtraTreesRegressor                  0.08
 ElasticNetCV                         0.03
 NuSVR                                0.02
 DummyRegressor                       0.00
 QuantileRegressor                    1.08
 SVR                                  0.02
 ExtraTreeRegressor                   0.01
 GradientBoostingRegressor            0.03
 XGBRegressor                         0.21
 DecisionTreeRegressor                0.01
 KernelRidge                          0.01
 LinearSVR                            0.01
 MLPRegressor                         0.21
 GaussianProcessRegressor             0.03  )

In [41]:
#hacer el modelo  HistGradientBoostingRegressor  de sklearn
from sklearn.ensemble import HistGradientBoostingRegressor as HGBR
hgb=HGBR()
hgb.fit(X_train, y_train)
#predecir con el modelo HistGradientBoostingRegressor
y_pred_hgb = hgb.predict(X_test)
#calcular el mse con el modelo HistGradientBoostingRegressor
from sklearn.metrics import mean_squared_error as mse
mse(y_test, y_pred_hgb, squared=False)

48641.97552759838

In [42]:
#reentrear el modelo HistGradientBoostingRegressor con todos los datos
hgb.fit(X, y)
#predecir con el modelo HistGradientBoostingRegressor con los datos de test
y_pred_hgb_test = hgb.predict(salaries_test)
#calcular el mse con el modelo HistGradientBoostingRegressor
mse(y_test, y_pred_hgb, squared=False)

48641.97552759838

In [44]:
#crear el dataframe con los resultados
df = pd.DataFrame({'salary_in_usd': y_pred_hgb_test})

df

     salary_in_usd
0         91407.46
1         52160.86
2         61303.51
3         75688.67
4         63217.63
..             ...
102       98122.69
103       76778.71
104      100091.47
105       53362.18
106       92017.42

[107 rows x 1 columns]

In [ ]:
#